name: Test and Validation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou a versão que você precisa

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint # substitua pelo seu comando de lint

      - name: Run tests
        run: npm test # ou outro comando de teste, se necessário

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD || echo "Changes detected"

  validate:
    runs-on: ubuntu-latest
    needs: test
    if: steps.check_changes.outputs.changed == 'true'
    steps:
      - name: Validate code
        run: |
          echo "Validating code..."
          # Adicione seus comandos de validação aqui, como verificar estilos, formatação, etc.
